version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3300:3000"
    volumes:
      - /usr/srf/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/srf/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]
